{
  "cve_id": "CVE-2024-22332",
  "timestamp": "2025-01-14 16:58:44",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:00"
    },
    "secondary": {
      "completed": false,
      "timestamp": null
    },
    "extraction": {
      "completed": false,
      "timestamp": null
    }
  },
  "urls": [
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/279972",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://https://www.ibm.com/support/pages/node/7116046",
      "status": "failed",
      "reason": "Failed to fetch content",
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}