{
  "cve_id": "CVE-2022-3644",
  "timestamp": "2025-01-14 16:58:57",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-08 10:43:28"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-09 11:55:05"
    },
    "extraction": {
      "completed": false,
      "timestamp": null
    }
  },
  "urls": [
    {
      "url": "https://github.com/pulp/pulp_ansible/blob/main/pulp_ansible/app/models.py#L234",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}