{
  "cve_id": "CVE-2023-38371",
  "timestamp": "2025-01-14 00:42:03",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:11"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:20"
    },
    "extraction": {
      "completed": false,
      "timestamp": null
    }
  },
  "urls": [
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/261198",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://www.ibm.com/support/pages/node/7158790",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}