{
  "cve_id": "CVE-2022-29217",
  "timestamp": "2025-01-14 16:58:34",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-08 10:43:26"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-09 11:54:58"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-09 22:16:02"
    }
  },
  "urls": [
    {
      "url": "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/jpadilla/pyjwt/releases/tag/2.4.0",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://www.vicarius.io/vsociety/posts/risky-algorithms-algorithm-confusion-in-pyjwt-cve-2022-29217",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}