{
  "cve_id": "CVE-2024-26151",
  "timestamp": "2025-01-14 00:42:13",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:01"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:32"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-12 10:35:06"
    }
  },
  "urls": [
    {
      "url": "https://github.com/FelixSchwarz/mjml-python/commit/84c495da20a91640a1ca551ace17df7f3be644aa",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/FelixSchwarz/mjml-python/commit/8d410b7a500703080bb14ed7e3d2663fe16767e6",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/FelixSchwarz/mjml-python/issues/52",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/FelixSchwarz/mjml-python/releases/tag/v0.11.0",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://github.com/FelixSchwarz/mjml-python/security/advisories/GHSA-578p-fxmm-6229",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    },
    {
      "url": "https://www.vicarius.io/vsociety/posts/cve-2024-26151-mjml-python-vulnerability-1",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-10 10:39:06"
    }
  ]
}