{
  "cve_id": "CVE-2022-43892",
  "timestamp": "2025-01-14 16:58:33",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:39:57"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:20"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-12 01:13:57"
    }
  },
  "urls": [
    {
      "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/240455",
      "status": "unknown",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://www.ibm.com/support/pages/node/7047202",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}