{
  "cve_id": "CVE-2024-34355",
  "timestamp": "2025-01-14 16:58:50",
  "phases": {
    "primary": {
      "completed": true,
      "timestamp": "2025-01-10 10:40:08"
    },
    "secondary": {
      "completed": true,
      "timestamp": "2025-01-11 20:55:57"
    },
    "extraction": {
      "completed": true,
      "timestamp": "2025-01-13 08:11:40"
    }
  },
  "urls": [
    {
      "url": "https://github.com/TYPO3/typo3/commit/56afa304ba8b5ad302e15df5def71bcc8d820375",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://github.com/TYPO3/typo3/security/advisories/GHSA-xjwx-78x7-q6jc",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    },
    {
      "url": "https://typo3.org/security/advisory/typo3-core-sa-2024-007",
      "status": "success",
      "reason": null,
      "timestamp": "2025-01-14 11:33:06"
    }
  ]
}